# Funding options for this project
# Add your preferred funding platforms here

# GitHub Sponsors
# github: [preethamdev05]

# Open Collective
# open_collective: face-recognition-attendance

# Ko-fi
# ko_fi: preethamdev05

# Custom
custom: ["https://www.buymeacoffee.com/preethamdev05"]
